<a href="https://colab.research.google.com/github/Stesilva16/Eng-de-dados--/blob/main/PandasMerge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importando bibliotecas

In [ ]:
import pandas as pd

In [ ]:
pd.set_option('display.max_columns',100)
#pd.set_option('display.max_rows', 10000)

## Extração dos Dados

In [ ]:
df = pd.read_csv('https://storage.googleapis.com/aulas-bc26-dados-gbs/cenipa/ocorrencia.csv', sep=';', encoding='ISO-8859-1', parse_dates=['ocorrencia_dia'], dayfirst=True)
df1 = pd.read_csv('https://storage.googleapis.com/aulas-bc26-dados-gbs/cenipa/fator_contribuinte.csv', sep=';')
df2 = pd.read_csv('https://storage.googleapis.com/aulas-bc26-dados-gbs/cenipa/aeronave.csv', sep=';')
df3 = pd.read_csv('https://storage.googleapis.com/aulas-bc26-dados-gbs/cenipa/ocorrencia_tipo.csv', sep=';')
df4 = pd.read_csv('https://storage.googleapis.com/aulas-bc26-dados-gbs/cenipa/recomendacao.csv', sep=';')

In [ ]:
dfback = df.copy()
dfback1 = df1.copy()
dfback2 = df2.copy()
dfback3 = df3.copy()
dfback4 = df4.copy()

## Tratamento df

In [ ]:
#drop colunas repetidas da df
df.drop(['codigo_ocorrencia1', 'codigo_ocorrencia2', 'codigo_ocorrencia3', 'codigo_ocorrencia4'], axis=1, inplace=True)
#drop colunas que não serão utilizadas da df
df.drop(['ocorrencia_latitude','ocorrencia_longitude','investigacao_aeronave_liberada','investigacao_status','divulgacao_relatorio_numero','divulgacao_relatorio_publicado','divulgacao_dia_publicacao'], axis=1, inplace=True)

In [ ]:
df.dtypes

codigo_ocorrencia                      int64
ocorrencia_classificacao              object
ocorrencia_cidade                     object
ocorrencia_uf                         object
ocorrencia_pais                       object
ocorrencia_aerodromo                  object
ocorrencia_dia                datetime64[ns]
ocorrencia_hora                       object
total_recomendacoes                    int64
total_aeronaves_envolvidas             int64
ocorrencia_saida_pista                object
dtype: object

In [ ]:
# renomear as colunas da df
df.rename(columns={
    'codigo_ocorrencia':'ocorrencia',
    'ocorrencia_classificacao':'classificacao',
    'ocorrencia_cidade':'cidade',
    'ocorrencia_uf':'uf',
    'ocorrencia_pais':'pais',
    'ocorrencia_aerodromo':'aerodromo',
    'ocorrencia_dia':'dia',
    'ocorrencia_hora':'horario',
    'total_recomendacoes':'recomendacoes',
    'total_aeronaves_envolvidas':'n_aeronaves',
    'ocorrencia_saida_pista':'saida_pista'
    }, inplace=True)

In [ ]:
df.dtypes

ocorrencia                int64
classificacao            object
cidade                   object
uf                       object
pais                     object
aerodromo                object
dia              datetime64[ns]
horario                  object
recomendacoes             int64
n_aeronaves               int64
saida_pista              object
dtype: object

In [ ]:
df.head(5)

,ocorrencia,classificacao,cidade,uf,pais,aerodromo,dia,horario,recomendacoes,n_aeronaves,saida_pista
0,81027,INCIDENTE GRAVE,SÃO PAULO,SP,BRASIL,SBSP,2022-10-09,16:30:00,0,1,SIM
1,81030,INCIDENTE,VITÓRIA,ES,BRASIL,SBVT,2022-10-09,16:20:00,0,1,NÃO
2,81023,INCIDENTE GRAVE,AMERICANA,SP,BRASIL,SDAI,2022-10-06,15:30:00,0,1,SIM
3,81029,INCIDENTE,BELO HORIZONTE,MG,BRASIL,SBBH,2022-10-06,00:44:00,0,1,NÃO
4,81025,INCIDENTE,MANAUS,AM,BRASIL,SBEG,2022-10-05,20:56:00,0,1,NÃO

## Tratamento df1

In [ ]:
# renomear as colunas da df1
df1.rename(columns={'codigo_ocorrencia3':'ocorrencia'}, inplace=True)

In [ ]:
df1.dtypes

ocorrencia              int64
fator_nome             object
fator_aspecto          object
fator_condicionante    object
fator_area             object
dtype: object

In [ ]:
df1.head(5)

,ocorrencia,fator_nome,fator_aspecto,fator_condicionante,fator_area
0,80383,ATITUDE,ASPECTO PSICOLÓGICO,INDIVIDUAL,FATOR HUMANO
1,80383,JULGAMENTO DE PILOTAGEM,DESEMPENHO DO SER HUMANO,OPERAÇÃO DA AERONAVE,FATOR OPERACIONAL
2,80383,PLANEJAMENTO DE VOO,DESEMPENHO DO SER HUMANO,OPERAÇÃO DA AERONAVE,FATOR OPERACIONAL
3,80383,SUPERVISÃO GERENCIAL,DESEMPENHO DO SER HUMANO,OPERAÇÃO DA AERONAVE,FATOR OPERACIONAL
4,80365,ATITUDE,ASPECTO PSICOLÓGICO,INDIVIDUAL,FATOR HUMANO

## Tratamento df2

In [ ]:
# renomear as colunas da df2
df2.rename(columns={'codigo_ocorrencia2':'ocorrencia'}, inplace=True)

In [ ]:
df2.dtypes

ocorrencia                       int64
aeronave_matricula              object
aeronave_operador_categoria     object
aeronave_tipo_veiculo           object
aeronave_fabricante             object
aeronave_modelo                 object
aeronave_tipo_icao              object
aeronave_motor_tipo             object
aeronave_motor_quantidade       object
aeronave_pmd                   float64
aeronave_pmd_categoria         float64
aeronave_assentos              float64
aeronave_ano_fabricacao        float64
aeronave_pais_fabricante        object
aeronave_pais_registro          object
aeronave_registro_categoria     object
aeronave_registro_segmento      object
aeronave_voo_origem             object
aeronave_voo_destino            object
aeronave_fase_operacao          object
aeronave_tipo_operacao          object
aeronave_nivel_dano             object
aeronave_fatalidades_total     float64
dtype: object

In [ ]:
df2.head(5)

,ocorrencia,aeronave_matricula,aeronave_operador_categoria,aeronave_tipo_veiculo,aeronave_fabricante,aeronave_modelo,aeronave_tipo_icao,aeronave_motor_tipo,aeronave_motor_quantidade,aeronave_pmd,aeronave_pmd_categoria,aeronave_assentos,aeronave_ano_fabricacao,aeronave_pais_fabricante,aeronave_pais_registro,aeronave_registro_categoria,aeronave_registro_segmento,aeronave_voo_origem,aeronave_voo_destino,aeronave_fase_operacao,aeronave_tipo_operacao,aeronave_nivel_dano,aeronave_fatalidades_total
0,43628,PTEHG,***,AVIÃO,EMBRAER,EMB-820C NAVAJO,PA31,PISTÃO,BIMOTOR,3175.0,3175.0,10.0,1976.0,BRASIL,BRASIL,AVIÃO,TÁXI AÉREO,DEPUTADO LUÍS EDUARDO MAGALHÃES,FAZENDA PONTAL,POUSO,TÁXI AÉREO,SUBSTANCIAL,0.0
1,43629,PTHVW,***,HELICÓPTERO,ROBINSON HELICOPTER,R22 BETA,R22,PISTÃO,MONOMOTOR,621.0,621.0,2.0,1991.0,BRASIL,BRASIL,HELICÓPTERO,INSTRUÇÃO,FORA DE AERODROMO,FORA DE AERODROMO,MANOBRA,INSTRUÇÃO,SUBSTANCIAL,0.0
2,43630,PTXRK,ESPECIALIZADA,AVIÃO,AIR TRACTOR,AT-401B,AT3P,PISTÃO,MONOMOTOR,2722.0,2722.0,1.0,1994.0,BRASIL,BRASIL,AVIÃO,ESPECIALIZADA,FORA DE AERODROMO,FORA DE AERODROMO,ESPECIALIZADA,ESPECIALIZADA,LEVE,0.0
3,43631,PRGGM,REGULAR,AVIÃO,BOEING COMPANY,737-8EH,B738,JATO,BIMOTOR,70533.0,70533.0,197.0,2009.0,BRASIL,BRASIL,AVIÃO,REGULAR,FORA DE AERODROMO,FORA DE AERODROMO,DESCIDA,REGULAR,NENHUM,0.0
4,43633,PRPSK,***,AVIÃO,EMBRAER,EMB-145LR,E145,JATO,BIMOTOR,21990.0,21990.0,54.0,2001.0,BRASIL,BRASIL,AVIÃO,REGULAR,FORA DE AERODROMO,FORA DE AERODROMO,CORRIDA APÓS POUSO,REGULAR,NENHUM,0.0

In [ ]:
# drop em coluna com dados repetidos
df2.drop(['aeronave_pmd_categoria','aeronave_registro_categoria','aeronave_pais_registro'], axis=1, inplace=True)

In [ ]:
df2.head(5)

,ocorrencia,aeronave_matricula,aeronave_operador_categoria,aeronave_tipo_veiculo,aeronave_fabricante,aeronave_modelo,aeronave_tipo_icao,aeronave_motor_tipo,aeronave_motor_quantidade,aeronave_pmd,aeronave_assentos,aeronave_ano_fabricacao,aeronave_pais_fabricante,aeronave_registro_segmento,aeronave_voo_origem,aeronave_voo_destino,aeronave_fase_operacao,aeronave_tipo_operacao,aeronave_nivel_dano,aeronave_fatalidades_total
0,43628,PTEHG,***,AVIÃO,EMBRAER,EMB-820C NAVAJO,PA31,PISTÃO,BIMOTOR,3175.0,10.0,1976.0,BRASIL,TÁXI AÉREO,DEPUTADO LUÍS EDUARDO MAGALHÃES,FAZENDA PONTAL,POUSO,TÁXI AÉREO,SUBSTANCIAL,0.0
1,43629,PTHVW,***,HELICÓPTERO,ROBINSON HELICOPTER,R22 BETA,R22,PISTÃO,MONOMOTOR,621.0,2.0,1991.0,BRASIL,INSTRUÇÃO,FORA DE AERODROMO,FORA DE AERODROMO,MANOBRA,INSTRUÇÃO,SUBSTANCIAL,0.0
2,43630,PTXRK,ESPECIALIZADA,AVIÃO,AIR TRACTOR,AT-401B,AT3P,PISTÃO,MONOMOTOR,2722.0,1.0,1994.0,BRASIL,ESPECIALIZADA,FORA DE AERODROMO,FORA DE AERODROMO,ESPECIALIZADA,ESPECIALIZADA,LEVE,0.0
3,43631,PRGGM,REGULAR,AVIÃO,BOEING COMPANY,737-8EH,B738,JATO,BIMOTOR,70533.0,197.0,2009.0,BRASIL,REGULAR,FORA DE AERODROMO,FORA DE AERODROMO,DESCIDA,REGULAR,NENHUM,0.0
4,43633,PRPSK,***,AVIÃO,EMBRAER,EMB-145LR,E145,JATO,BIMOTOR,21990.0,54.0,2001.0,BRASIL,REGULAR,FORA DE AERODROMO,FORA DE AERODROMO,CORRIDA APÓS POUSO,REGULAR,NENHUM,0.0

## Tratamento df3

In [ ]:
# renomear as colunas da df3
df3.rename(columns={'codigo_ocorrencia1':'ocorrencia'}, inplace=True)

In [ ]:
df3.dtypes

ocorrencia                    int64
ocorrencia_tipo              object
ocorrencia_tipo_categoria    object
taxonomia_tipo_icao          object
dtype: object

In [ ]:
df3.head(5)

,ocorrencia,ocorrencia_tipo,ocorrencia_tipo_categoria,taxonomia_tipo_icao
0,81030,DESCOMPRESSÃO NÃO INTENCIONAL / EXPLOSIVA,FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPON...,SCF-NP
1,81029,ESTOURO DE PNEU,FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPON...,SCF-NP
2,81027,ESTOURO DE PNEU,FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPON...,SCF-NP
3,81027,EXCURSÃO DE PISTA,EXCURSÃO DE PISTA,RE
4,81026,FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPON...,FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPON...,SCF-NP

## Tratamento df4

In [ ]:
# renomear as colunas da df4
df4.rename(columns={'codigo_ocorrencia4':'ocorrencia'}, inplace=True)

In [ ]:
df4.dtypes

ocorrencia                          int64
recomendacao_numero                object
recomendacao_dia_assinatura        object
recomendacao_dia_encaminhamento    object
recomendacao_dia_feedback          object
recomendacao_conteudo              object
recomendacao_status                object
recomendacao_destinatario_sigla    object
recomendacao_destinatario          object
dtype: object

In [ ]:
df4.head(5)

,ocorrencia,recomendacao_numero,recomendacao_dia_assinatura,recomendacao_dia_encaminhamento,recomendacao_dia_feedback,recomendacao_conteudo,recomendacao_status,recomendacao_destinatario_sigla,recomendacao_destinatario
0,80258,A-137/CENIPA/2019 - 01,2021-11-16,2021-12-23,2022-01-26,Atuar junto ao operador do Aeródromo de Tangar...,IMPLEMENTADA,ANAC,AGÊNCIA NACIONAL DE AVIAÇÃO CIVIL
1,80252,A-094/CENIPA/2021 - 01,2022-09-21,2022-09-27,NaN,Atuar junto ao proprietário da área não cadast...,AGUARDANDO RESPOSTA,ANAC,AGÊNCIA NACIONAL DE AVIAÇÃO CIVIL
2,80073,A-063/CENIPA/2021 - 01,2021-11-12,2021-11-19,2021-12-02,Divulgar os ensinamentos colhidos nesta invest...,IMPLEMENTADA,ANAC,AGÊNCIA NACIONAL DE AVIAÇÃO CIVIL
3,80073,A-063/CENIPA/2021 - 02,2021-11-12,2021-11-19,2021-12-02,Divulgar os ensinamentos colhidos nesta invest...,IMPLEMENTADA,ANAC,AGÊNCIA NACIONAL DE AVIAÇÃO CIVIL
4,79997,A-050/CENIPA/2021 - 01,2022-08-05,2022-08-11,NaN,Reforçar a atuação junto à Pulveriza Aviação A...,AGUARDANDO RESPOSTA,ANAC,AGÊNCIA NACIONAL DE AVIAÇÃO CIVIL

In [ ]:
#drop colunas que não serão utilizadas da df2
df4.drop(['recomendacao_dia_assinatura', 'recomendacao_dia_encaminhamento', 'recomendacao_dia_feedback'], axis=1, inplace=True)
#drop colunas que repetidas da df2
df4.drop(['recomendacao_destinatario_sigla'], axis=1, inplace=True)

In [ ]:
df4.head(5)

,ocorrencia,recomendacao_numero,recomendacao_conteudo,recomendacao_status,recomendacao_destinatario
0,80258,A-137/CENIPA/2019 - 01,Atuar junto ao operador do Aeródromo de Tangar...,IMPLEMENTADA,AGÊNCIA NACIONAL DE AVIAÇÃO CIVIL
1,80252,A-094/CENIPA/2021 - 01,Atuar junto ao proprietário da área não cadast...,AGUARDANDO RESPOSTA,AGÊNCIA NACIONAL DE AVIAÇÃO CIVIL
2,80073,A-063/CENIPA/2021 - 01,Divulgar os ensinamentos colhidos nesta invest...,IMPLEMENTADA,AGÊNCIA NACIONAL DE AVIAÇÃO CIVIL
3,80073,A-063/CENIPA/2021 - 02,Divulgar os ensinamentos colhidos nesta invest...,IMPLEMENTADA,AGÊNCIA NACIONAL DE AVIAÇÃO CIVIL
4,79997,A-050/CENIPA/2021 - 01,Reforçar a atuação junto à Pulveriza Aviação A...,AGUARDANDO RESPOSTA,AGÊNCIA NACIONAL DE AVIAÇÃO CIVIL

## Merge dff1

In [ ]:
#criando data frame agregado
#outer = o que encontrar de relação ele adiciona, e o que não encontrar ele repete 
#inner = usar quando você quer todas as colunas preenchidas
dff1 = df.merge(df1, how='outer')
dff1.head(5)

,ocorrencia,classificacao,cidade,uf,pais,aerodromo,dia,horario,recomendacoes,n_aeronaves,saida_pista,fator_nome,fator_aspecto,fator_condicionante,fator_area
0,81027,INCIDENTE GRAVE,SÃO PAULO,SP,BRASIL,SBSP,2022-10-09,16:30:00,0,1,SIM,NaN,NaN,NaN,NaN
1,81030,INCIDENTE,VITÓRIA,ES,BRASIL,SBVT,2022-10-09,16:20:00,0,1,NÃO,NaN,NaN,NaN,NaN
2,81023,INCIDENTE GRAVE,AMERICANA,SP,BRASIL,SDAI,2022-10-06,15:30:00,0,1,SIM,NaN,NaN,NaN,NaN
3,81029,INCIDENTE,BELO HORIZONTE,MG,BRASIL,SBBH,2022-10-06,00:44:00,0,1,NÃO,NaN,NaN,NaN,NaN
4,81025,INCIDENTE,MANAUS,AM,BRASIL,SBEG,2022-10-05,20:56:00,0,1,NÃO,NaN,NaN,NaN,NaN

## Merge ddf2

In [ ]:
#criando data frame agregado
#outer = o que encontrar de relação ele adiciona, e o que não encontrar ele repete 
#inner = usar quando você quer todas as colunas preenchidas
dff2 = dff1.merge(df2, how='outer')
dff2.head(5)

,ocorrencia,classificacao,cidade,uf,pais,aerodromo,dia,horario,recomendacoes,n_aeronaves,saida_pista,fator_nome,fator_aspecto,fator_condicionante,fator_area,aeronave_matricula,aeronave_operador_categoria,aeronave_tipo_veiculo,aeronave_fabricante,aeronave_modelo,aeronave_tipo_icao,aeronave_motor_tipo,aeronave_motor_quantidade,aeronave_pmd,aeronave_assentos,aeronave_ano_fabricacao,aeronave_pais_fabricante,aeronave_registro_segmento,aeronave_voo_origem,aeronave_voo_destino,aeronave_fase_operacao,aeronave_tipo_operacao,aeronave_nivel_dano,aeronave_fatalidades_total
0,81027,INCIDENTE GRAVE,SÃO PAULO,SP,BRASIL,SBSP,2022-10-09,16:30:00,0,1,SIM,NaN,NaN,NaN,NaN,PPMIX,***,AVIÃO,BOMBARDIER,LEARJET 45(75),***,JATO,SEM TRAÇÃO,9752.0,0.0,0.0,BRASIL,PARTICULAR,CATARATAS,CONGONHAS,CORRIDA APÓS POUSO,PRIVADA,LEVE,0.0
1,81030,INCIDENTE,VITÓRIA,ES,BRASIL,SBVT,2022-10-09,16:20:00,0,1,NÃO,NaN,NaN,NaN,NaN,PRAUQ,***,AVIÃO,EMBRAER,ERJ 190-200 IGW,E190,JATO,BIMOTOR,52290.0,125.0,2015.0,BRASIL,REGULAR,TANCREDO NEVES,EURICO DE AGUIAR SALLES,CRUZEIRO,REGULAR,NENHUM,0.0
2,81023,INCIDENTE GRAVE,AMERICANA,SP,BRASIL,SDAI,2022-10-06,15:30:00,0,1,SIM,NaN,NaN,NaN,NaN,PPGSV,***,AVIÃO,NEIVA INDUSTRIA AERONAUTICA,56-C,PAUL,PISTÃO,MONOMOTOR,660.0,2.0,1960.0,BRASIL,INSTRUÇÃO,AMERICANA,AERODRÓMO ESTADUAL DE CAMPINAS / AMARAIS,DECOLAGEM,INSTRUÇÃO,LEVE,0.0
3,81029,INCIDENTE,BELO HORIZONTE,MG,BRASIL,SBBH,2022-10-06,00:44:00,0,1,NÃO,NaN,NaN,NaN,NaN,PTVMB,***,AVIÃO,NEIVA INDUSTRIA AERONAUTICA,EMB-810D,PA34,PISTÃO,BIMOTOR,2155.0,4.0,1990.0,BRASIL,PARTICULAR,JACAREPAGUÁ,CARLOS DRUMMOND DE ANDRADE / PAMPULHA,CORRIDA APÓS POUSO,PRIVADA,LEVE,0.0
4,81025,INCIDENTE,MANAUS,AM,BRASIL,SBEG,2022-10-05,20:56:00,0,1,NÃO,NaN,NaN,NaN,NaN,PTWRU,***,ANFÍBIO,CESSNA AIRCRAFT,208 ANFIBIO,C208,TURBOÉLICE,MONOMOTOR,3629.0,10.0,1998.0,BRASIL,TÁXI AÉREO,EDUARDO GOMES,EDUARDO GOMES,CORRIDA APÓS POUSO,PRIVADA,LEVE,0.0

## Merge dff3

In [ ]:
dff3 = dff2.merge(df3, how='outer')
dff3.head(5)

,ocorrencia,classificacao,cidade,uf,pais,aerodromo,dia,horario,recomendacoes,n_aeronaves,saida_pista,fator_nome,fator_aspecto,fator_condicionante,fator_area,aeronave_matricula,aeronave_operador_categoria,aeronave_tipo_veiculo,aeronave_fabricante,aeronave_modelo,aeronave_tipo_icao,aeronave_motor_tipo,aeronave_motor_quantidade,aeronave_pmd,aeronave_assentos,aeronave_ano_fabricacao,aeronave_pais_fabricante,aeronave_registro_segmento,aeronave_voo_origem,aeronave_voo_destino,aeronave_fase_operacao,aeronave_tipo_operacao,aeronave_nivel_dano,aeronave_fatalidades_total,ocorrencia_tipo,ocorrencia_tipo_categoria,taxonomia_tipo_icao
0,81027,INCIDENTE GRAVE,SÃO PAULO,SP,BRASIL,SBSP,2022-10-09,16:30:00,0,1,SIM,NaN,NaN,NaN,NaN,PPMIX,***,AVIÃO,BOMBARDIER,LEARJET 45(75),***,JATO,SEM TRAÇÃO,9752.0,0.0,0.0,BRASIL,PARTICULAR,CATARATAS,CONGONHAS,CORRIDA APÓS POUSO,PRIVADA,LEVE,0.0,ESTOURO DE PNEU,FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPON...,SCF-NP
1,81027,INCIDENTE GRAVE,SÃO PAULO,SP,BRASIL,SBSP,2022-10-09,16:30:00,0,1,SIM,NaN,NaN,NaN,NaN,PPMIX,***,AVIÃO,BOMBARDIER,LEARJET 45(75),***,JATO,SEM TRAÇÃO,9752.0,0.0,0.0,BRASIL,PARTICULAR,CATARATAS,CONGONHAS,CORRIDA APÓS POUSO,PRIVADA,LEVE,0.0,EXCURSÃO DE PISTA,EXCURSÃO DE PISTA,RE
2,81030,INCIDENTE,VITÓRIA,ES,BRASIL,SBVT,2022-10-09,16:20:00,0,1,NÃO,NaN,NaN,NaN,NaN,PRAUQ,***,AVIÃO,EMBRAER,ERJ 190-200 IGW,E190,JATO,BIMOTOR,52290.0,125.0,2015.0,BRASIL,REGULAR,TANCREDO NEVES,EURICO DE AGUIAR SALLES,CRUZEIRO,REGULAR,NENHUM,0.0,DESCOMPRESSÃO NÃO INTENCIONAL / EXPLOSIVA,FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPON...,SCF-NP
3,81023,INCIDENTE GRAVE,AMERICANA,SP,BRASIL,SDAI,2022-10-06,15:30:00,0,1,SIM,NaN,NaN,NaN,NaN,PPGSV,***,AVIÃO,NEIVA INDUSTRIA AERONAUTICA,56-C,PAUL,PISTÃO,MONOMOTOR,660.0,2.0,1960.0,BRASIL,INSTRUÇÃO,AMERICANA,AERODRÓMO ESTADUAL DE CAMPINAS / AMARAIS,DECOLAGEM,INSTRUÇÃO,LEVE,0.0,EXCURSÃO DE PISTA,EXCURSÃO DE PISTA,RE
4,81023,INCIDENTE GRAVE,AMERICANA,SP,BRASIL,SDAI,2022-10-06,15:30:00,0,1,SIM,NaN,NaN,NaN,NaN,PPGSV,***,AVIÃO,NEIVA INDUSTRIA AERONAUTICA,56-C,PAUL,PISTÃO,MONOMOTOR,660.0,2.0,1960.0,BRASIL,INSTRUÇÃO,AMERICANA,AERODRÓMO ESTADUAL DE CAMPINAS / AMARAIS,DECOLAGEM,INSTRUÇÃO,LEVE,0.0,PERDA DE CONTROLE NO SOLO,PERDA DE CONTROLE NO SOLO,LOC-G

## Merge dff4

In [ ]:
dff4 = dff3.merge(df4, how='outer')
dff4.head(5)

,ocorrencia,classificacao,cidade,uf,pais,aerodromo,dia,horario,recomendacoes,n_aeronaves,saida_pista,fator_nome,fator_aspecto,fator_condicionante,fator_area,aeronave_matricula,aeronave_operador_categoria,aeronave_tipo_veiculo,aeronave_fabricante,aeronave_modelo,aeronave_tipo_icao,aeronave_motor_tipo,aeronave_motor_quantidade,aeronave_pmd,aeronave_assentos,aeronave_ano_fabricacao,aeronave_pais_fabricante,aeronave_registro_segmento,aeronave_voo_origem,aeronave_voo_destino,aeronave_fase_operacao,aeronave_tipo_operacao,aeronave_nivel_dano,aeronave_fatalidades_total,ocorrencia_tipo,ocorrencia_tipo_categoria,taxonomia_tipo_icao,recomendacao_numero,recomendacao_conteudo,recomendacao_status,recomendacao_destinatario
0,81027,INCIDENTE GRAVE,SÃO PAULO,SP,BRASIL,SBSP,2022-10-09,16:30:00,0,1,SIM,NaN,NaN,NaN,NaN,PPMIX,***,AVIÃO,BOMBARDIER,LEARJET 45(75),***,JATO,SEM TRAÇÃO,9752.0,0.0,0.0,BRASIL,PARTICULAR,CATARATAS,CONGONHAS,CORRIDA APÓS POUSO,PRIVADA,LEVE,0.0,ESTOURO DE PNEU,FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPON...,SCF-NP,NaN,NaN,NaN,NaN
1,81027,INCIDENTE GRAVE,SÃO PAULO,SP,BRASIL,SBSP,2022-10-09,16:30:00,0,1,SIM,NaN,NaN,NaN,NaN,PPMIX,***,AVIÃO,BOMBARDIER,LEARJET 45(75),***,JATO,SEM TRAÇÃO,9752.0,0.0,0.0,BRASIL,PARTICULAR,CATARATAS,CONGONHAS,CORRIDA APÓS POUSO,PRIVADA,LEVE,0.0,EXCURSÃO DE PISTA,EXCURSÃO DE PISTA,RE,NaN,NaN,NaN,NaN
2,81030,INCIDENTE,VITÓRIA,ES,BRASIL,SBVT,2022-10-09,16:20:00,0,1,NÃO,NaN,NaN,NaN,NaN,PRAUQ,***,AVIÃO,EMBRAER,ERJ 190-200 IGW,E190,JATO,BIMOTOR,52290.0,125.0,2015.0,BRASIL,REGULAR,TANCREDO NEVES,EURICO DE AGUIAR SALLES,CRUZEIRO,REGULAR,NENHUM,0.0,DESCOMPRESSÃO NÃO INTENCIONAL / EXPLOSIVA,FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPON...,SCF-NP,NaN,NaN,NaN,NaN
3,81023,INCIDENTE GRAVE,AMERICANA,SP,BRASIL,SDAI,2022-10-06,15:30:00,0,1,SIM,NaN,NaN,NaN,NaN,PPGSV,***,AVIÃO,NEIVA INDUSTRIA AERONAUTICA,56-C,PAUL,PISTÃO,MONOMOTOR,660.0,2.0,1960.0,BRASIL,INSTRUÇÃO,AMERICANA,AERODRÓMO ESTADUAL DE CAMPINAS / AMARAIS,DECOLAGEM,INSTRUÇÃO,LEVE,0.0,EXCURSÃO DE PISTA,EXCURSÃO DE PISTA,RE,NaN,NaN,NaN,NaN
4,81023,INCIDENTE GRAVE,AMERICANA,SP,BRASIL,SDAI,2022-10-06,15:30:00,0,1,SIM,NaN,NaN,NaN,NaN,PPGSV,***,AVIÃO,NEIVA INDUSTRIA AERONAUTICA,56-C,PAUL,PISTÃO,MONOMOTOR,660.0,2.0,1960.0,BRASIL,INSTRUÇÃO,AMERICANA,AERODRÓMO ESTADUAL DE CAMPINAS / AMARAIS,DECOLAGEM,INSTRUÇÃO,LEVE,0.0,PERDA DE CONTROLE NO SOLO,PERDA DE CONTROLE NO SOLO,LOC-G,NaN,NaN,NaN,NaN

## Filtros

In [ ]:
ftcodigo = dff1.ocorrencia == 80383
dff1.loc[ftcodigo]

,ocorrencia,classificacao,cidade,uf,pais,aerodromo,dia,horario,recomendacoes,n_aeronaves,saida_pista,fator_nome,fator_aspecto,fator_condicionante,fator_area
542,80383,ACIDENTE,LAGOA DA CONFUSÃO,TO,BRASIL,***,2021-11-11,12:40:00,0,1,NÃO,ATITUDE,ASPECTO PSICOLÓGICO,INDIVIDUAL,FATOR HUMANO
543,80383,ACIDENTE,LAGOA DA CONFUSÃO,TO,BRASIL,***,2021-11-11,12:40:00,0,1,NÃO,JULGAMENTO DE PILOTAGEM,DESEMPENHO DO SER HUMANO,OPERAÇÃO DA AERONAVE,FATOR OPERACIONAL
544,80383,ACIDENTE,LAGOA DA CONFUSÃO,TO,BRASIL,***,2021-11-11,12:40:00,0,1,NÃO,PLANEJAMENTO DE VOO,DESEMPENHO DO SER HUMANO,OPERAÇÃO DA AERONAVE,FATOR OPERACIONAL
545,80383,ACIDENTE,LAGOA DA CONFUSÃO,TO,BRASIL,***,2021-11-11,12:40:00,0,1,NÃO,SUPERVISÃO GERENCIAL,DESEMPENHO DO SER HUMANO,OPERAÇÃO DA AERONAVE,FATOR OPERACIONAL

In [ ]:
ft2018 = dff1.dia.dt.year == 2018
dff1.loc[ft2018]

,ocorrencia,classificacao,cidade,uf,pais,aerodromo,dia,horario,recomendacoes,n_aeronaves,saida_pista,fator_nome,fator_aspecto,fator_condicionante,fator_area
2511,78394,ACIDENTE,CALDAS NOVAS,GO,BRASIL,***,2018-12-31,11:50:00,0,1,NÃO,NaN,NaN,NaN,NaN
2512,78406,INCIDENTE,GUARULHOS,SP,BRASIL,***,2018-12-30,17:30:00,0,1,NÃO,NaN,NaN,NaN,NaN
2513,78390,ACIDENTE,ARACAJU,SE,BRASIL,***,2018-12-29,15:30:00,1,1,NÃO,APLICAÇÃO DE COMANDOS,DESEMPENHO DO SER HUMANO,OPERAÇÃO DA AERONAVE,FATOR OPERACIONAL
2514,78390,ACIDENTE,ARACAJU,SE,BRASIL,***,2018-12-29,15:30:00,1,1,NÃO,ATITUDE,ASPECTO PSICOLÓGICO,INDIVIDUAL,FATOR HUMANO
2515,78390,ACIDENTE,ARACAJU,SE,BRASIL,***,2018-12-29,15:30:00,1,1,NÃO,INDISCIPLINA DE VOO,DESEMPENHO DO SER HUMANO,OPERAÇÃO DA AERONAVE,FATOR OPERACIONAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3302,77616,INCIDENTE GRAVE,PORTO SEGURO,BA,BRASIL,***,2018-01-04,20:45:00,0,1,NÃO,NaN,NaN,NaN,NaN
3303,77617,INCIDENTE,CAMPO GRANDE,AL,BRASIL,SBCG,2018-01-04,20:44:00,0,1,NÃO,NaN,NaN,NaN,NaN
3304,77631,INCIDENTE,BELO HORIZONTE,MG,BRASIL,SBBH,2018-01-04,16:08:00,0,1,NÃO,NaN,NaN,NaN,NaN
3305,77607,INCIDENTE,PORTO SEGURO,BA,BRASIL,SBPS,2018-01-03,11:36:00,0,1,NÃO,NaN,NaN,NaN,NaN
3306,77608,INCIDENTE GRAVE,ARROIO GRANDE,RS,BRASIL,***,2018-01-03,13:51:00,0,1,NÃO,NaN,NaN,NaN,NaN